sudo: required

services:
  - docker

env:
  global:
    - LIBIMOBILEDEVICE_WIN32_VERSION=v1.2.72
  matrix:
    - DISTRIBUTION=bionic
    - DISTRIBUTION=xenial
    - DISTRIBUTION=xenial-arm64
    - DISTRIBUTION=alpine
    - DISTRIBUTION=bionic-arm64

before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce

script:
  - echo Packaging libimobiledevice version $LIBIMOBILEDEVICE_WIN32_VERSION for $DISTRIBUTION
  - docker --version
  - docker run --rm --privileged multiarch/qemu-user-static:register
  - docker build --build-arg LIBIMOBILEDEVICE_WIN32_VERSION=$LIBIMOBILEDEVICE_WIN32_VERSION -t quamotion/usbmuxd:$LIBIMOBILEDEVICE_WIN32_VERSION-$DISTRIBUTION $DISTRIBUTION

# The Docker images are published from the imobiledevice-net/release pipeline in Azure
# after_success:
#  - docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
#  - docker push quamotion/usbmuxd:$LIBIMOBILEDEVICE_WIN32_VERSION-$DISTRIBUTION
